name: Deploy Azure Function(isolated)
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - run: dotnet publish QueueTriggerFn -c Release -o publish # here QueueTriggerFn is the folder path inside that .sln exist
      - uses: azure/functions-action@v1
        with:
          app-name: "my-az-functionapp"
          package: "publish"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
